name: smart_task_manager_ui
description: A Smart Task Manager Flutter app with AI auto-classification
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  provider: ^6.0.0
  flutter_riverpod: ^2.4.0
  intl: ^0.19.0
  connectivity_plus: ^5.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
